// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: star.proto

package star

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BotStatusRequestStatusType int32

const (
	BotStatusRequest_waiting    BotStatusRequestStatusType = 0
	BotStatusRequest_connecting BotStatusRequestStatusType = 1
	BotStatusRequest_close      BotStatusRequestStatusType = 2
)

// Enum value maps for BotStatusRequestStatusType.
var (
	BotStatusRequestStatusType_name = map[int32]string{
		0: "waiting",
		1: "connecting",
		2: "close",
	}
	BotStatusRequestStatusType_value = map[string]int32{
		"waiting":    0,
		"connecting": 1,
		"close":      2,
	}
)

func (x BotStatusRequestStatusType) Enum() *BotStatusRequestStatusType {
	p := new(BotStatusRequestStatusType)
	*p = x
	return p
}

func (x BotStatusRequestStatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BotStatusRequestStatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_star_proto_enumTypes[0].Descriptor()
}

func (BotStatusRequestStatusType) Type() protoreflect.EnumType {
	return &file_star_proto_enumTypes[0]
}

func (x BotStatusRequestStatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BotStatusRequestStatusType.Descriptor instead.
func (BotStatusRequestStatusType) EnumDescriptor() ([]byte, []int) {
	return file_star_proto_rawDescGZIP(), []int{1, 0}
}

type BotStatusRequestGenderType int32

const (
	BotStatusRequest_man   BotStatusRequestGenderType = 0
	BotStatusRequest_woman BotStatusRequestGenderType = 1
)

// Enum value maps for BotStatusRequestGenderType.
var (
	BotStatusRequestGenderType_name = map[int32]string{
		0: "man",
		1: "woman",
	}
	BotStatusRequestGenderType_value = map[string]int32{
		"man":   0,
		"woman": 1,
	}
)

func (x BotStatusRequestGenderType) Enum() *BotStatusRequestGenderType {
	p := new(BotStatusRequestGenderType)
	*p = x
	return p
}

func (x BotStatusRequestGenderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BotStatusRequestGenderType) Descriptor() protoreflect.EnumDescriptor {
	return file_star_proto_enumTypes[1].Descriptor()
}

func (BotStatusRequestGenderType) Type() protoreflect.EnumType {
	return &file_star_proto_enumTypes[1]
}

func (x BotStatusRequestGenderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BotStatusRequestGenderType.Descriptor instead.
func (BotStatusRequestGenderType) EnumDescriptor() ([]byte, []int) {
	return file_star_proto_rawDescGZIP(), []int{1, 1}
}

type PInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CityId   int32  `protobuf:"varint,1,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	Country  string `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Region   string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Province string `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	City     string `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Isp      string `protobuf:"bytes,6,opt,name=isp,proto3" json:"isp,omitempty"`
}

func (x *PInfo) Reset() {
	*x = PInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_star_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PInfo) ProtoMessage() {}

func (x *PInfo) ProtoReflect() protoreflect.Message {
	mi := &file_star_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PInfo.ProtoReflect.Descriptor instead.
func (*PInfo) Descriptor() ([]byte, []int) {
	return file_star_proto_rawDescGZIP(), []int{0}
}

func (x *PInfo) GetCityId() int32 {
	if x != nil {
		return x.CityId
	}
	return 0
}

func (x *PInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *PInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PInfo) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *PInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *PInfo) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}

type BotStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotId   string                     `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	X       float32                    `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y       float32                    `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	EyeX    float32                    `protobuf:"fixed32,4,opt,name=eye_x,json=eyeX,proto3" json:"eye_x,omitempty"`
	EyeY    float32                    `protobuf:"fixed32,5,opt,name=eye_y,json=eyeY,proto3" json:"eye_y,omitempty"`
	Msg     string                     `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`
	RealX   float32                    `protobuf:"fixed32,7,opt,name=real_x,json=realX,proto3" json:"real_x,omitempty"`
	RealY   float32                    `protobuf:"fixed32,8,opt,name=real_y,json=realY,proto3" json:"real_y,omitempty"`
	Status  BotStatusRequestStatusType `protobuf:"varint,9,opt,name=status,proto3,enum=BotStatusRequestStatusType" json:"status,omitempty"`
	Name    string                     `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Gender  BotStatusRequestGenderType `protobuf:"varint,11,opt,name=gender,proto3,enum=BotStatusRequestGenderType" json:"gender,omitempty"`
	PosInfo *PInfo                     `protobuf:"bytes,12,opt,name=pos_info,json=posInfo,proto3" json:"pos_info,omitempty"`
}

func (x *BotStatusRequest) Reset() {
	*x = BotStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_star_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotStatusRequest) ProtoMessage() {}

func (x *BotStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_star_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotStatusRequest.ProtoReflect.Descriptor instead.
func (*BotStatusRequest) Descriptor() ([]byte, []int) {
	return file_star_proto_rawDescGZIP(), []int{1}
}

func (x *BotStatusRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *BotStatusRequest) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BotStatusRequest) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BotStatusRequest) GetEyeX() float32 {
	if x != nil {
		return x.EyeX
	}
	return 0
}

func (x *BotStatusRequest) GetEyeY() float32 {
	if x != nil {
		return x.EyeY
	}
	return 0
}

func (x *BotStatusRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BotStatusRequest) GetRealX() float32 {
	if x != nil {
		return x.RealX
	}
	return 0
}

func (x *BotStatusRequest) GetRealY() float32 {
	if x != nil {
		return x.RealY
	}
	return 0
}

func (x *BotStatusRequest) GetStatus() BotStatusRequestStatusType {
	if x != nil {
		return x.Status
	}
	return BotStatusRequest_waiting
}

func (x *BotStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BotStatusRequest) GetGender() BotStatusRequestGenderType {
	if x != nil {
		return x.Gender
	}
	return BotStatusRequest_man
}

func (x *BotStatusRequest) GetPosInfo() *PInfo {
	if x != nil {
		return x.PosInfo
	}
	return nil
}

type BotStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotStatus []*BotStatusRequest `protobuf:"bytes,1,rep,name=bot_status,json=botStatus,proto3" json:"bot_status,omitempty"`
}

func (x *BotStatusResponse) Reset() {
	*x = BotStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_star_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotStatusResponse) ProtoMessage() {}

func (x *BotStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_star_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotStatusResponse.ProtoReflect.Descriptor instead.
func (*BotStatusResponse) Descriptor() ([]byte, []int) {
	return file_star_proto_rawDescGZIP(), []int{2}
}

func (x *BotStatusResponse) GetBotStatus() []*BotStatusRequest {
	if x != nil {
		return x.BotStatus
	}
	return nil
}

var File_star_proto protoreflect.FileDescriptor

var file_star_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x94, 0x01, 0x0a,
	0x05, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x73, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x69, 0x73, 0x70, 0x22, 0xae, 0x03, 0x0a, 0x10, 0x62, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x6f, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x13, 0x0a, 0x05, 0x65,
	0x79, 0x65, 0x5f, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x65, 0x79, 0x65, 0x58,
	0x12, 0x13, 0x0a, 0x05, 0x65, 0x79, 0x65, 0x5f, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x04, 0x65, 0x79, 0x65, 0x59, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x6c, 0x5f,
	0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x58, 0x12, 0x15,
	0x0a, 0x06, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05,
	0x72, 0x65, 0x61, 0x6c, 0x59, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x62, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x35, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1d, 0x2e, 0x62, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x52,
	0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x07, 0x70, 0x6f, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x35, 0x0a, 0x0b, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x77, 0x61, 0x69,
	0x74, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x10,
	0x02, 0x22, 0x21, 0x0a, 0x0b, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x07, 0x0a, 0x03, 0x6d, 0x61, 0x6e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x77, 0x6f, 0x6d,
	0x61, 0x6e, 0x10, 0x01, 0x22, 0x45, 0x0a, 0x11, 0x62, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x62, 0x6f, 0x74,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x62, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x09, 0x62, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x08, 0x5a, 0x06, 0x2e,
	0x3b, 0x73, 0x74, 0x61, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_star_proto_rawDescOnce sync.Once
	file_star_proto_rawDescData = file_star_proto_rawDesc
)

func file_star_proto_rawDescGZIP() []byte {
	file_star_proto_rawDescOnce.Do(func() {
		file_star_proto_rawDescData = protoimpl.X.CompressGZIP(file_star_proto_rawDescData)
	})
	return file_star_proto_rawDescData
}

var file_star_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_star_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_star_proto_goTypes = []interface{}{
	(BotStatusRequestStatusType)(0), // 0: botStatusRequest.status_type
	(BotStatusRequestGenderType)(0), // 1: botStatusRequest.gender_type
	(*PInfo)(nil),                   // 2: pInfo
	(*BotStatusRequest)(nil),        // 3: botStatusRequest
	(*BotStatusResponse)(nil),       // 4: botStatusResponse
}
var file_star_proto_depIdxs = []int32{
	0, // 0: botStatusRequest.status:type_name -> botStatusRequest.status_type
	1, // 1: botStatusRequest.gender:type_name -> botStatusRequest.gender_type
	2, // 2: botStatusRequest.pos_info:type_name -> pInfo
	3, // 3: botStatusResponse.bot_status:type_name -> botStatusRequest
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_star_proto_init() }
func file_star_proto_init() {
	if File_star_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_star_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_star_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_star_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_star_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_star_proto_goTypes,
		DependencyIndexes: file_star_proto_depIdxs,
		EnumInfos:         file_star_proto_enumTypes,
		MessageInfos:      file_star_proto_msgTypes,
	}.Build()
	File_star_proto = out.File
	file_star_proto_rawDesc = nil
	file_star_proto_goTypes = nil
	file_star_proto_depIdxs = nil
}
