// Code generated by protoc-gen-go. DO NOT EDIT.
// source: star.proto

package star

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BotStatusRequestStatusType int32

const (
	BotStatusRequest_waiting    BotStatusRequestStatusType = 0
	BotStatusRequest_connecting BotStatusRequestStatusType = 1
	BotStatusRequest_close      BotStatusRequestStatusType = 2
)

var BotStatusRequestStatusType_name = map[int32]string{
	0: "waiting",
	1: "connecting",
	2: "close",
}

var BotStatusRequestStatusType_value = map[string]int32{
	"waiting":    0,
	"connecting": 1,
	"close":      2,
}

func (x BotStatusRequestStatusType) String() string {
	return proto.EnumName(BotStatusRequestStatusType_name, int32(x))
}

func (BotStatusRequestStatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3eaf02c9100040aa, []int{0, 0}
}

type BotStatusRequestGenderType int32

const (
	BotStatusRequest_man   BotStatusRequestGenderType = 0
	BotStatusRequest_woman BotStatusRequestGenderType = 1
)

var BotStatusRequestGenderType_name = map[int32]string{
	0: "man",
	1: "woman",
}

var BotStatusRequestGenderType_value = map[string]int32{
	"man":   0,
	"woman": 1,
}

func (x BotStatusRequestGenderType) String() string {
	return proto.EnumName(BotStatusRequestGenderType_name, int32(x))
}

func (BotStatusRequestGenderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3eaf02c9100040aa, []int{0, 1}
}

type BotStatusRequest struct {
	BotId                string                     `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	X                    float32                    `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32                    `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	EyeX                 float32                    `protobuf:"fixed32,4,opt,name=eye_x,json=eyeX,proto3" json:"eye_x,omitempty"`
	EyeY                 float32                    `protobuf:"fixed32,5,opt,name=eye_y,json=eyeY,proto3" json:"eye_y,omitempty"`
	Msg                  string                     `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`
	RealX                float32                    `protobuf:"fixed32,7,opt,name=real_x,json=realX,proto3" json:"real_x,omitempty"`
	RealY                float32                    `protobuf:"fixed32,8,opt,name=real_y,json=realY,proto3" json:"real_y,omitempty"`
	Status               BotStatusRequestStatusType `protobuf:"varint,9,opt,name=status,proto3,enum=BotStatusRequestStatusType" json:"status,omitempty"`
	Name                 string                     `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Gender               BotStatusRequestGenderType `protobuf:"varint,11,opt,name=gender,proto3,enum=BotStatusRequestGenderType" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *BotStatusRequest) Reset()         { *m = BotStatusRequest{} }
func (m *BotStatusRequest) String() string { return proto.CompactTextString(m) }
func (*BotStatusRequest) ProtoMessage()    {}
func (*BotStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf02c9100040aa, []int{0}
}

func (m *BotStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotStatusRequest.Unmarshal(m, b)
}
func (m *BotStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotStatusRequest.Marshal(b, m, deterministic)
}
func (m *BotStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotStatusRequest.Merge(m, src)
}
func (m *BotStatusRequest) XXX_Size() int {
	return xxx_messageInfo_BotStatusRequest.Size(m)
}
func (m *BotStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BotStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BotStatusRequest proto.InternalMessageInfo

func (m *BotStatusRequest) GetBotId() string {
	if m != nil {
		return m.BotId
	}
	return ""
}

func (m *BotStatusRequest) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *BotStatusRequest) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *BotStatusRequest) GetEyeX() float32 {
	if m != nil {
		return m.EyeX
	}
	return 0
}

func (m *BotStatusRequest) GetEyeY() float32 {
	if m != nil {
		return m.EyeY
	}
	return 0
}

func (m *BotStatusRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *BotStatusRequest) GetRealX() float32 {
	if m != nil {
		return m.RealX
	}
	return 0
}

func (m *BotStatusRequest) GetRealY() float32 {
	if m != nil {
		return m.RealY
	}
	return 0
}

func (m *BotStatusRequest) GetStatus() BotStatusRequestStatusType {
	if m != nil {
		return m.Status
	}
	return BotStatusRequest_waiting
}

func (m *BotStatusRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BotStatusRequest) GetGender() BotStatusRequestGenderType {
	if m != nil {
		return m.Gender
	}
	return BotStatusRequest_man
}

type BotStatusResponse struct {
	BotStatus            []*BotStatusRequest `protobuf:"bytes,1,rep,name=bot_status,json=botStatus,proto3" json:"bot_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BotStatusResponse) Reset()         { *m = BotStatusResponse{} }
func (m *BotStatusResponse) String() string { return proto.CompactTextString(m) }
func (*BotStatusResponse) ProtoMessage()    {}
func (*BotStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf02c9100040aa, []int{1}
}

func (m *BotStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotStatusResponse.Unmarshal(m, b)
}
func (m *BotStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotStatusResponse.Marshal(b, m, deterministic)
}
func (m *BotStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotStatusResponse.Merge(m, src)
}
func (m *BotStatusResponse) XXX_Size() int {
	return xxx_messageInfo_BotStatusResponse.Size(m)
}
func (m *BotStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BotStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BotStatusResponse proto.InternalMessageInfo

func (m *BotStatusResponse) GetBotStatus() []*BotStatusRequest {
	if m != nil {
		return m.BotStatus
	}
	return nil
}

func init() {
	proto.RegisterEnum("BotStatusRequestStatusType", BotStatusRequestStatusType_name, BotStatusRequestStatusType_value)
	proto.RegisterEnum("BotStatusRequestGenderType", BotStatusRequestGenderType_name, BotStatusRequestGenderType_value)
	proto.RegisterType((*BotStatusRequest)(nil), "botStatusRequest")
	proto.RegisterType((*BotStatusResponse)(nil), "botStatusResponse")
}

func init() {
	proto.RegisterFile("star.proto", fileDescriptor_3eaf02c9100040aa)
}

var fileDescriptor_3eaf02c9100040aa = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x6e, 0xf2, 0x30,
	0x10, 0x84, 0x31, 0x21, 0xe1, 0xcf, 0xe6, 0x17, 0x0a, 0x5b, 0x55, 0xf2, 0xa5, 0x52, 0x9a, 0x53,
	0x4e, 0xa8, 0xa2, 0xe2, 0x11, 0x7a, 0xe8, 0x35, 0xbd, 0xc0, 0x29, 0x72, 0x60, 0x85, 0x90, 0xc0,
	0xa6, 0xb1, 0x11, 0xf1, 0x33, 0xf4, 0xa5, 0x2b, 0x3b, 0x34, 0x8d, 0x5a, 0xf5, 0xb6, 0xf3, 0x79,
	0x35, 0x33, 0xd6, 0x02, 0x68, 0x23, 0x9a, 0xc5, 0xb9, 0x51, 0x46, 0xe5, 0x1f, 0x01, 0xa4, 0xb5,
	0x32, 0x6f, 0x46, 0x98, 0x8b, 0x2e, 0xe9, 0xfd, 0x42, 0xda, 0xe0, 0x3d, 0x44, 0xb5, 0x32, 0xd5,
	0x61, 0xc7, 0x59, 0xc6, 0x8a, 0xb8, 0x0c, 0x6b, 0x65, 0x5e, 0x77, 0xf8, 0x1f, 0x58, 0xcb, 0xc7,
	0x19, 0x2b, 0xc6, 0x25, 0x6b, 0x9d, 0xb2, 0x3c, 0xe8, 0x94, 0xc5, 0x3b, 0x08, 0xc9, 0x52, 0xd5,
	0xf2, 0x89, 0x27, 0x13, 0xb2, 0xb4, 0xfe, 0x82, 0x96, 0x87, 0x3d, 0xdc, 0x60, 0x0a, 0xc1, 0x49,
	0xef, 0x79, 0xe4, 0x9d, 0xdd, 0xe8, 0xe2, 0x1a, 0x12, 0xc7, 0xaa, 0xe5, 0x53, 0xbf, 0x17, 0x3a,
	0xb5, 0xee, 0xb1, 0xe5, 0xff, 0xbe, 0xf1, 0x06, 0x57, 0x10, 0x69, 0xdf, 0x96, 0xc7, 0x19, 0x2b,
	0x66, 0xcb, 0x87, 0xc5, 0xcf, 0xfe, 0x8b, 0xee, 0xbd, 0x32, 0xf6, 0x4c, 0xe5, 0x6d, 0x19, 0x11,
	0x26, 0x52, 0x9c, 0x88, 0x83, 0xcf, 0xf5, 0xb3, 0xb3, 0xda, 0x93, 0xdc, 0x51, 0xc3, 0x93, 0xbf,
	0xac, 0xba, 0xf7, 0x9b, 0x55, 0x27, 0xf2, 0x15, 0x24, 0x83, 0x04, 0x4c, 0x60, 0x7a, 0x15, 0x07,
	0x73, 0x90, 0xfb, 0x74, 0x84, 0x33, 0x80, 0xad, 0x92, 0x92, 0xb6, 0x5e, 0x33, 0x8c, 0x21, 0xdc,
	0x1e, 0x95, 0xa6, 0x74, 0x9c, 0x3f, 0x42, 0x32, 0x70, 0xc3, 0x29, 0x04, 0x27, 0x21, 0xd3, 0x91,
	0x5b, 0xb9, 0x2a, 0x37, 0xb2, 0xfc, 0x05, 0xe6, 0x83, 0x06, 0xfa, 0xac, 0xa4, 0x26, 0x7c, 0x02,
	0x70, 0xd7, 0xb8, 0x7d, 0x9a, 0x65, 0x41, 0x91, 0x2c, 0xe7, 0xbf, 0x9a, 0x96, 0x71, 0x4f, 0xea,
	0xc8, 0xdf, 0xf6, 0xf9, 0x33, 0x00, 0x00, 0xff, 0xff, 0xe8, 0xdd, 0x8d, 0x55, 0xe9, 0x01, 0x00,
	0x00,
}
